~No such command!
~break [state|-]       set get and reset breakpoint state (qb)
~help [command]        help with using the program
~info                  show all information about this machine
~limit [steps|-        set get and reset number of steps
~load filename.t36     load t36 file
~prog [from][to]       show program
~quit                  exit the program
~reg [0..7]            show register content
~reset                 reset program
~restore               restore machine to original state
~run [head position]   run from data tape head position
~step [head position]  run step-by-step from data tape head position
~symbol [symbols|-]    set get and reset symbol set (S)
~tape [0..5][filename]`show content or assign file or device to tape
~trace [on|off]        turn tracking on and off
~The STAT value is bad or missing.
~The STAT value is out of range.
~The SPOS value is bad.
~The SPOS value is out of range.
~The program file was successfully loaded.
~Description:      
~Command parameter is bad or missing.
~Command parameter value is incorrect.
~No breakpoint state set.
~The breakpoint state is 
~The breakpoint state is deleted.
~The breakpoint state is set to 
~Number of states: 
~The number of states is set to 
~Set of symbols:   
~The symbols are deleted.
~The symbols are set to 
~Duplicate symbols have been deleted!
~The symbol list is too long and has been truncated!
~No loaded program!
~Cannot read 
~Program name:     
~The tape is empty.
~Assigned tape files:
~The tape content is deleted.
~The program has been reset.
~The tape data is too long and has been truncated!
~Run program from head position 
~Step-by-step execution head position 
~Trace on.
~Trace off.
~The initial state (qi) is bad or missing.
~The initial state value (qi) is not included in the set Q.
~The head moving direction value is not included in the set D.
~The final state (qm) is bad or missing.
~The final state value (qm) is not included in the set Q.
~The read symbol (sj) is not in the set S.
~The symbol to be written (sk) is not in the set S.
~Missing mandatory PROG BEGIN tag.
~Missing mandatory PROG END tag.
~Missing mandatory CARD BEGIN tag.
~Missing mandatory CARD END tag.
~Missing optional TAPE END tag.
~Missing optional COMM END tag.
~Missing mandatory CARD tag.
~Missing mandatory NAME tag.
~Missing mandatory STAT tag.
~Missing mandatory SYMB tag.
~Head position:    
~Program:
~Commands:
~The Turing machine has been restore.
~The Turing machine has started.
~The Turing machine has stopped.
~count  head  qi  sj  sk  D  qm
~The scanned symbol is not in the symbol set.
~The number of steps has reached the maximum.
~No program step limit set.
~The program step limit is 
~The program step limit is deleted.
~The program step limit is set to 
~Press any key to continue!
~The set breakpoint state has been reached.
~The specified head position is invalid ignored.
~The specified head position is out of range ignored.
~Temporary starting head position set:  
~Memory allocation failed!
~Bad tuple!
~Register content:
~  r0 (ACC):
~  r1 (DTP):
~  r2 (PTP):
~  r3 (RTP):
~  r4 (STP):
~  r5 (TTP):
~  r6 (PSC):
~  r7 (IR): 
~  t0 (output device):    
~  t1 (data tape):        
~  t2 (user program tape):
~  t3 (result tape):      
~  t4 (stack tape):       
~  t5 (temporary tape):   
