~No such command!
~break [0..255|-]            set, get and reset breakpoint state (qb)
~help [command]              help with using the program
~info                        show all information about this machine
~limit [10..32767|-]         set, get and reset number of steps
~load filename.t36           load t36 file
~prog                        show program
~quit                        exit the program
~registers                   show all register content
~reset                       reset program
~restore                     restore machine to original state
~run [0..255]                run program step-by-step from head position
~step [0..255]               run program step-by-step from head position
~symbol [symbols|-]          set, get and reset symbol set (S)
~tape [d36|p36|r36|s36|t36]  show tape content
~trace [on|off]              turn tracking on and off
